[package]
name = "onesource"
version = "0.0.0"
license = "MIT"
description = "Placeholder"
edition = "2021"
[dependencies]
clap = { version = "4.0", features = ["derive"] }
globset = "0.4.18"
ignore = "0.4.25"
